### PR TITLE
Add missing french translations

### PR DESCRIPTION
**Pull request by damsfx**

### CODE REVIEW

**Comment by mjauvin** [comment]
@damsfx please use double quotes instead of escaping the single quote character.

**Comment by damsfx** [comment]
> @damsfx please use double quotes instead of escaping the single quote character.

I did this for the keys I added.
Throughout the file, there are disparities in the use of the escape character and double quotes.

You wanted me to standardize the whole file?

**Comment by mjauvin** [comment]
> > @damsfx please use double quotes instead of escaping the single quote character.
> 
> I did this for the keys I added. Throughout the file, there are disparities in the use of the escape character and double quotes.
> 
> You wanted me to standardize the whole file?

No, I thought I saw some you added that were missing this, I was wrong it seems (I was on mobile when I checked this)

**Comment by mjauvin** [comment]
Oh, by the way, you added this to the wrong repo... these are repo used for composer.

**Comment by damsfx** [comment]
> Oh, by the way, you added this to the wrong repo... these are repo used for composer.

Where did I think I was going!
I really have to stop working too late at night.

**Pull request closed without merging**
